---
- name: EDA | Webhook | Listen for events on a webhook and trigger an AAP WF
  hosts: localhost

 ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: EDA | Webhook | Run workflow to greet our webhook callers
      condition: event.payload.name == 'greeting'
      actions:
        - run_workflow_template:
            name: "[EDA] Webhook to workflow"
            organization: Default
